### ISSUE TITLE
Build for 64-bit please?

### ISSUE THREAD

**Issue by AlexUrrutia** [mesmotronic/air-ane-androidid#1]
Can you provide a 64 bit compatible ANE please? Thanks!

[https://github.com/Gamua/Adobe-Runtime-Support](url)

**Comment by neilrackett** [comment]
I've added a pre-release build [here](https://github.com/mesmotronic/air-ane-androidid/releases), which I'll replace with an official release once AIR 33 is out of beta.

Feel free to [buy us a coffee](http://bit.ly/2PpsoLn) if you find it useful ;-)
