### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hamraee** [mesmotronic/air-ane-androidid#2]
Hi
I have a question. If it is possible: 
How can I use 
"https://github.com/mesmotronic/air-ane-androidid" inside Adobe flash?

**Comment by neilrackett** [comment]
If you mean as part of a SWF, then no, ANEs can only be used with Adobe AIR.

If you're asking how to add an ANE to an Adobe Flash/Animate project, see https://www.youtube.com/watch?v=ik-vfeqzToY.

**Comment by hamraee** [comment]
OK, I will see it but in this link: https://github.com/mesmotronic/air-ane-androidid there are several folders and files, Do we need them? and I can't see the ANE file

**Comment by neilrackett** [comment]
https://github.com/mesmotronic/air-ane-androidid/releases

**Comment by hamraee** [comment]
Special thanks for your support. I don't know where is the problem! Can you add .fla Source that contains all code? I will add ANE library.

**Comment by hamraee** [comment]
This is my fla file

[yyaaa3.zip](https://github.com/mesmotronic/air-ane-androidid/files/3400367/yyaaa3.zip)

**Comment by neilrackett** [comment]
Please refer to the code code example in the [README.md](https://github.com/mesmotronic/air-ane-androidid/blob/master/README.md) file.

**Comment by hamraee** [comment]
I work with adobe flash and adobe animate:
Please check these steps and tell me that is something wrong:
---->For this line:

"Enables Adobe AIR 3.1+ for Android to access ANDROID_ID. That's it."
I can choose Air 23 for target.
---->For this:
Adds about 2KB to your app. Released under BSD license.

app.xml
com.mesmotronic.ane.androidid

I created a XML file and added above content inside of it. In adobe flash "purplish setting" ---> "General" tab I included my XML file.

---->Also I add ANE file as you showed in your video (YouTube)

-----> Last step I added following code:

import com.mesmotronic.ane.AndroidID;

trace(AndroidID.ANDROID_ID);
--------------------------------------------------------That 's it---------------------------------

**Comment by hamraee** [comment]
Neilrackett 
I 'm waiting for your response....
Thanks in advance.

**Comment by neilrackett** [comment]
Please ensure that you are using version 1.0.0 of the ANE and not the prerelease version 1.0.64, unless you are already using Adobe AIR 33 SDK.

Beyond that, we are not able to offer any further technical support regarding integration with Adobe Flash / Animate.

**Comment by hamraee** [comment]
Thanks a lot for your response.
Where can I read version  of the ANE?
