### ISSUE TITLE
Different Android ID

### ISSUE THREAD

**Issue by hamraee** [mesmotronic/air-ane-androidid#4]
Hello:
I test blew code in Android Studio An the result for Android ID differ from this ANE inside Adobe Animate

import android.provider.Settings.Secure;
private String android_id = Secure.getString(getContext().getContentResolver(),
                                                        Secure.ANDROID_ID); 
[Link and reference](https://stackoverflow.com/questions/2785485/is-there-a-unique-android-device-id/2785493#2785493)

**Comment by neilrackett** [comment]
This ANE appears to be working as expected: is it possible that the Android Studio test is running in a different profile to the AIR app from Adobe Animate?

If you work out a better solution, we'd be happy to consider a PR.
